# Generated by Django 5.2.7 on 2025-11-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='ppublished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
