# Generated by Django 5.2.7 on 2025-11-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_published_date_post_ppublished_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ppublished_date',
            new_name='published_date',
        ),
    ]
